### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by WolfY-SnipeS** [cryptolok/USBlok#2]
makes no sense to me what do i have to do, to turn my usb into badusb what do i do and what do i need plz need help

**Comment by cryptolok** [comment]
Well, my good sir, the first thing to do, In My Hackish Opinion, is to learn some English :) since communication is essential in our daily life.
Now about the testing because, I think that your question is about it, my solution protects not only from [BadUSB](https://github.com/brandonlw/Psychson), but also from social engineering.
Fewer examples are [USB Rubber Ducky](http://usbrubberducky.com/#!index.md), [LAN Turtle](https://hakshop.com/collections/lan-turtle/products/lan-turtle), [USB armory](https://inversepath.com/usbarmory) and so on.
Have fun :)
